name: conversation_bubbles
description: 'Enables you to show Android Conversation Bubbles from your Flutter app.'
version: 0.0.1
homepage: https://github.com/keepdeploying/conversation_bubbles 

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.keepdeploying.conversation_bubbles
        pluginClass: ConversationBubblesPlugin
